import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BootLoader from "@/components/BootLoader";
import TopChrome from "@/components/TopChrome";
import { CursorTagProvider } from "@/components/CursorTag";
import { site } from "@/lib/content";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const description =
  "Full-Stack Web Developer and AI Engineer building ERP and finance platforms, RAG assistants, and backend systems with Python, LangChain and LangGraph.";

export const metadata: Metadata = {
  // Required for next/og (opengraph-image.tsx) and the sitemap to resolve
  // absolute URLs. Update alongside `site.url` in src/lib/content.ts if a
  // custom domain replaces the Vercel one.
  metadataBase: new URL(site.url),
  title: `${site.name} - ${site.role}`,
  description,
  openGraph: {
    title: `${site.name} - ${site.role}`,
    description,
    url: site.url,
    siteName: site.name,
    type: "website",
    locale: "en_US",
    // og:image is generated by src/app/opengraph-image.tsx and wired in
    // automatically by the file convention; no `images` entry needed here.
  },
  twitter: {
    card: "summary_large_image",
    title: `${site.name} - ${site.role}`,
    description,
    // twitter:image comes from src/app/twitter-image.tsx the same way.
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <BootLoader />
        <CursorTagProvider>
          <TopChrome />
          {children}
        </CursorTagProvider>
      </body>
    </html>
  );
}
